### ISSUE TITLE
Configure_Firefox.ps1

### ISSUE THREAD

**Issue by Hellements** [farag2/Mozilla-Firefox#2]
Hello @farag2 
Thank you for the scripts updates.
The Configure_Firefox.ps1 script is not running the "install extensions" part on lines 132 to 139.
I'm not a coder, just curious. That command on line 136 "userChrome.css" is correct?
Thank you, friend.

**Comment by farag2** [comment]
The error screen?)

**Comment by farag2** [comment]
> That command on line 136 "userChrome.css" is correct?

Yup, this is the valid folder name. It's not related to Chrome browser.

**Comment by Hellements** [comment]
Hey @farag2 , thank you for your reply.
So I was testing the new Configure_Firefox.ps1 that you updated recently.
There's no error screen, but I noticed the script is not installing the extensions as specified on lines 132 to 139. Isn't it supposed to run the other "Add_Firefox_Extensions.ps1" script?
Another thing is that on line 136, the script is replacing the content of the "good" userChrome.css from chrome folder with a copy of the Add_Firefox_Extensions.ps1 content. That's why I asked you before about the userChrome.css as OutFile on line 136.
For me it's not a big problem because I'm using my own Add_Firefox_Extensions.ps1 file with all the extensions I need. I'm just letting you know because other people are probably using it too.
As always, thank you so much and have a great week.

**Comment by farag2** [comment]
Well, if so you need to configure the script before running, right?) You suggest to move all code from that file to the current one without invoking it?.. OK.

**Comment by farag2** [comment]
Added the appropriate comment.
